openapi: 3.0.0
info:
  title: Campfire API
  version: 0.1.0

servers:
  - url: http://localhost:8080

components:
  schemas:
    Campfire:
      type: object
      properties:
        id: 
          type: number
        topic:
          type: string
        participants: 
          type: number
          description: The total number of participants
      required:
        - id
        - topic
        - participants
    Comment:
      type: object
      properties:
        id: 
          type: number
        content: 
          type: string
      required:
        - id
        - content
  responses:
    Default:
      description: Response indicating whether the operation is a success
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: string
                enum: [success, error]
paths:
  /campfire:
    get:
      operationId: getCampfire
      description: Get all campfires
      parameters:
        - in: query
          name: topic
          schema:
            type: string
            example: covid
        - in: query
          name: limit
          schema:
            description: The maximum number of results
            type: number
            example: 5
        - in: query
          name: random
          schema:
            description: Retrieve campfires randomly. This overrides topic
            type: boolean
        - in: query
          name: id
          schema:
            description: The id of the campfire
            type: number
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  campfires:
                    type: array
                    items:
                      $ref: "#/components/schemas/Campfire"
    post:
      operationId: postCampfire
      description: Add a new campfire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topic:
                  type: string
                  example: covid
              required:
                - topic
      responses:
        200:
          $ref: "#/components/responses/Default"

  /campfire/{id}/participate:
    post:
      operationId: postCampfireParticipate
      description: Participate in a campfire
      parameters:
        - in: path
          name: id
          schema:
            type: number
            description: The id of the campfire
      responses:
        200:
          $ref: "#/components/responses/Default"

  /campfire/{:id}/comment:
    get:
      operationId: getCampfireComment
      description: Randomly get a comment from a campfire
      parameters:
        - in: path
          name: id
          schema:
            type: number
            description: The id of the campfire
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    $ref: "#/components/schemas/Comment"
                required: 
                  - comment
        403:
          description: The number of comments per campfire is limited to 1 each day
  /campfire/comment:
    post:
      operationId: postCampfireComment
      description: Leave a comment for a campfire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  description: The id of the campfire
                content:
                  type: string
                  description: The content of the comment
              required:
                - id
                - content
      responses:
        200:
          $ref: "#/components/responses/Default"

  /analytics/campfire/trending:
    get:
      operationId: getCampfireTrending
      description: Get the top campfires
      parameters:
        - in: query
          name: limit
          schema:
            type: number
            description: The number of trending campfires to retrieve
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  campfires:
                    type: array
                    items:
                      $ref: "#/components/schemas/Campfire"